TechnicalTest/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TechnicalTest.Models;
using TechnicalTest.Repositories;
using TechnicalTest.BusinessLogic;
using TechnicalTest.BusinessLogic.DataModel;
using System.Web.Script.Serialization;

namespace TechnicalTest.Controllers
{
    public class AssignmentController : Controller
    {
        [HttpPost]
        public ActionResult UploadFiles()
        {

            string path = Server.MapPath("~/FileData/");
            HttpFileCollectionBase files = Request.Files;
            string physicalpath = string.Empty;
            for (int i = 0; i < files.Count; i++)
            {
                HttpPostedFileBase file = files[i];
                if (file.FileName.EndsWith(".xml"))
                {
                    file.SaveAs(path + file.FileName);
                    physicalpath = file.FileName;
                }
                else
                {
                    throw new Exception("Invalid File Type. File type must be XML");
                }
            }
            return Json(physicalpath);
        }
        [HttpPost]
        public ActionResult UploadCSVFiles()
        {

            string path = Server.MapPath("~/FileData/");
            HttpFileCollectionBase files = Request.Files;
            string physicalpath = string.Empty;
            for (int i = 0; i < files.Count; i++)
            {
                HttpPostedFileBase file = files[i];
                if (file.FileName.EndsWith(".csv"))
                {
                    file.SaveAs(path + file.FileName);
                    physicalpath = file.FileName;
                }
                else
                {
                    throw new Exception("Invalid File Type. File type must be XML");
                }
            }
            return Json(physicalpath);
        }
        public ActionResult ViewUploadedResults()
        {
            return View();
        }
        public ActionResult CSVAssignment()
        {
            FileUploadViewModel viewModel = new FileUploadViewModel();
            return View(viewModel);
        }
        public ActionResult XMLAssignment()
        {
            FileUploadViewModel viewModel = new FileUploadViewModel();
            return View(viewModel);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult XMLAssignment(FileUploadViewModel paramModel)
        {
            if (ModelState.IsValid)
            {
                if (paramModel != null)
                {
                    List<TransactionInfo> results = AppRepositoryManager.XMLReaderManager.RetrunListOfProducts(paramModel.XMLFileLocation);
                    bool IsSuccessDB = AppRepositoryManager.DataAccessManager.InsertXMLData(results);
                    ViewBag.Result = "true";
                    return View(paramModel);
                }
                else
                {
                    ViewBag.Result = "false";
                    FileUploadViewModel newModel = new FileUploadViewModel();
                    return View(newModel);
                }
            }
            FileUploadViewModel createmodel = new FileUploadViewModel();
            return View(createmodel);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult CSVAssignment(FileUploadViewModel paramModel)
        {
            if (ModelState.IsValid)
            {
                if (paramModel != null)
                {
                    List<TransactionInfo> results = AppRepositoryManager.CSVReaderManager.RetrunListOfProducts(paramModel.CSVFileLocation);
                    bool IsSuccessDB = AppRepositoryManager.DataAccessManager.InsertCSVData(results);
                    ViewBag.Result = "true";
                    return View(paramModel);
                }
                else
                {
                    ViewBag.Result = "false";
                    FileUploadViewModel newModel = new FileUploadViewModel();
                    return View(newModel);
                }
            }
            FileUploadViewModel createmodel = new FileUploadViewModel();
            return View(createmodel);
        }
        [HttpPost]
        public ActionResult GetUploadedData(string curCode, string status,string fromdate, string todate)
        {
            List<TransactionInfo> lstFinalResult = new List<TransactionInfo>();
            DateTime fromDate;
            DateTime toDate;
            lstFinalResult = AppRepositoryManager.DataAccessManager.GetGridData(curCode, DateTime.Now, DateTime.Now, status);
            if (fromdate != string.Empty && todate != string.Empty)
            {
                fromDate = StringToDateTime_MMddyyyy(fromdate);
                toDate = StringToDateTime_MMddyyyy(todate);

                var date_linq_filter = from dateResult in lstFinalResult
                                       where dateResult.TransactionDate.Date >= fromDate.Date && dateResult.TransactionDate.Date <= toDate.Date
                                       select dateResult;
                if (date_linq_filter.Count() > 0)
                {
                    lstFinalResult = new List<TransactionInfo>();
                    lstFinalResult = date_linq_filter.ToList<TransactionInfo>();
                }
                else
                {
                    lstFinalResult = new List<TransactionInfo>();
                }
            }

            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(lstFinalResult.ToList());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        private DateTime StringToDateTime_MMddyyyy(String txtDate)
        {
            try
            {
                string Vdatetime;
                string Vday;
                string Vmonth;
                string Vyear;
                Vdatetime = txtDate.Trim();
                Vday = Vdatetime.Substring(0, 2);
                Vmonth = Vdatetime.Substring(3, 2);
                Vyear = Vdatetime.Substring(6, 4);
                return new DateTime(Convert.ToInt16(Vyear), Convert.ToInt16(Vmonth), Convert.ToInt16(Vday), DateTime.Now.Hour,
                                     DateTime.Now.Minute, DateTime.Now.Second);
            }
            catch
            {
                return DateTime.MinValue;
            }
        }
    }
}

TechnicalTest/Views/Assignment/CSVAssignment.cshtml
@using TechnicalTest.Models
@model FileUploadViewModel
@{
    ViewBag.Title = "CSV Assignment";
    Layout = "~/Views/Shared/AdminLayout.cshtml";

    string viewMode = String.Empty;
}
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">CSV Assignment</a>
                </li>
                <li class="active">Upload</li>
            </ul><!-- /.breadcrumb -->
        </div>

        <div class="page-content" style="font-family:Zawgyi-One;">
            <div class="row">
                <div class="col-xs-12">

                    @using (Html.BeginForm("CSVAssignment", "Assignment", FormMethod.Post, new { @class = "form-horizontal", role = "form", AutoComplete = "off" }))
                    {
                        @Html.AntiForgeryToken()
                        if (ViewBag.Result == "true")
                        {
                            <div class="alert alert-block alert-success">
                                <button type="button" class="close" data-dismiss="alert">
                                    <i class="ace-icon fa fa-times"></i>
                                </button>

                                <p>
                                    <strong>
                                        <i class="ace-icon fa fa-check"></i>
                                        Well done!
                                    </strong>
                                    You successfully read this important alert message.
                                </p>

                                <p>
                                    <a href="/Assignment/ViewUploadedResults" class="btn btn-sm btn-success">View List</a>
                                </p>
                            </div>
                        }
                        else if (ViewBag.Result == "false")
                        {
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert">
                                    <i class="ace-icon fa fa-times"></i>
                                </button>

                                <strong>
                                    <i class="ace-icon fa fa-times"></i>
                                    Oh snap!
                                </strong>

                                Change a few things up and try submitting again.
                                <br />
                            </div>
                        }

                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CSVFileLocation, htmlAttributes: new { @class = "control-label col-md-2" })
                               
                                <div class="col-xs-3">
                                    <input type="file" id="id-input-file-2" />
                                    <input type="hidden" value="@Model.CSVFileLocation" name="CSVFileLocation" id="CSVFileLocation" />
                                    <input type="hidden" value="defaultvalue" name="XMLFileLocation" id="XMLFileLocation" />
                                    <span id="uploadresult"></span>
                                    @Html.ValidationMessageFor(model => model.CSVFileLocation, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-xs-3">
                                    <img src="~/Content/Image/loading.gif" id="loadingImg" style="width:35px;height:35px;" />
                                </div>

                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" id="btnsubmit" class="btn btn-default" />
                                </div>
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <!-- basic scripts -->
    <!--[if !IE]> -->
    <script src="/assets/js/jquery-2.1.4.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")

    <!-- <![endif]-->
    <!--[if IE]> to use
    <script src="assets/js/jquery-1.11.3.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        if ('ontouchstart' in document.documentElement) document.write("<script src='/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>
    <script src="/assets/js/bootstrap.min.js"></script>

    <!-- page specific plugin scripts -->
    <!--[if lte IE 8]>
      <script src="assets/js/excanvas.min.js"></script>
    <![endif]-->
    <script src="/assets/js/jquery-ui.custom.min.js"></script>
    <script src="/assets/js/jquery.ui.touch-punch.min.js"></script>
    <script src="/assets/js/chosen.jquery.min.js"></script>
    <script src="/assets/js/spinbox.min.js"></script>
    <script src="/assets/js/bootstrap-datepicker.min.js"></script>
    <script src="/assets/js/bootstrap-timepicker.min.js"></script>
    <script src="/assets/js/moment.min.js"></script>
    <script src="/assets/js/daterangepicker.min.js"></script>
    <script src="/assets/js/bootstrap-datetimepicker.min.js"></script>
    <script src="/assets/js/bootstrap-colorpicker.min.js"></script>
    <script src="/assets/js/jquery.knob.min.js"></script>
    <script src="/assets/js/autosize.min.js"></script>
    <script src="/assets/js/jquery.inputlimiter.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/bootstrap-tag.min.js"></script>

    <script src="/Scripts/summernote.js"></script>
    <script src="/Scripts/script-custom-editor.js"></script>
    <link href="/css/summernote.css" rel="stylesheet" />

    <!-- ace scripts -->
    <script src="/assets/js/ace-elements.min.js"></script>
    <script src="/assets/js/ace.min.js"></script>
    <script type="text/javascript">
        jQuery(function ($) {
            $("#loadingImg").css("display", "none");
            $('#id-input-file-2').ace_file_input({
                no_file: 'No File ...',
                btn_choose: 'Choose',
                btn_change: 'Change',
                droppable: false,
                onchange: null,
                thumbnail: false, //| true | large
                //whitelist:'gif|png|jpg|jpeg'
                //blacklist:'exe|php'
                //onchange:''
                //
            }).on('change', function () {
                var files = $("#id-input-file-2").get(0).files;
                var fileData = new FormData();

                for (var i = 0; i < files.length; i++) {
                    fileData.append("fileInput", files[i]);
                }

                $.ajax({
                    type: "POST",
                    url: "/Assignment/UploadCSVFiles",
                    dataType: "json",
                    contentType: false, // Not to set any content header
                    processData: false, // Not to process data
                    data: fileData,
                    success: function (result, status, xhr) {
                        $("#CSVFileLocation").val(result);
                        $("#uploadresult").html("<font color='green'>Uploaded successfully</font>");
                    },
                    error: function (xhr, status, error) {
                        if (xhr.responseText.indexOf("Invalid File Type") >= 0) {
                            $("#uploadresult").html("<font color='Red'>Unknown format</font>");
                        }
                        else {
                            $("#uploadresult").html(status);
                        }

                    }
                });
            });

            $(document).ajaxStart(function () {
                $("#loadingImg").show();
                $("#btnsubmit").prop('disabled', true);
            });

            $(document).ajaxStop(function () {
                $("#loadingImg").hide();
                $("#btnsubmit").prop('disabled', false);
            });
        });
    </script>


}

TechnicalTest/Views/Assignment/XMLAssignment.cshtml
@using TechnicalTest.Models
@model FileUploadViewModel
@{
    ViewBag.Title = "XML Assignment";
    Layout = "~/Views/Shared/AdminLayout.cshtml";

    string viewMode = String.Empty;
}
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">XML Assignment</a>
                </li>
                <li class="active">Upload</li>
            </ul><!-- /.breadcrumb -->
        </div>

        <div class="page-content" style="font-family:Zawgyi-One;">
            <div class="row">
                <div class="col-xs-12">

                    @using (Html.BeginForm("XMLAssignment", "Assignment", FormMethod.Post, new { @class = "form-horizontal", role = "form", AutoComplete = "off" }))
                    {
                        @Html.AntiForgeryToken()
                        if (ViewBag.Result == "true")
                        {
                            <div class="alert alert-block alert-success">
                                <button type="button" class="close" data-dismiss="alert">
                                    <i class="ace-icon fa fa-times"></i>
                                </button>

                                <p>
                                    <strong>
                                        <i class="ace-icon fa fa-check"></i>
                                        Well done!
                                    </strong>
                                    You successfully read this important alert message.
                                </p>

                                <p>
                                    <a href="/Assignment/ViewUploadedResults" class="btn btn-sm btn-success">View List</a>
                                </p>
                            </div>
                        }
                        else if (ViewBag.Result == "false")
                        {
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert">
                                    <i class="ace-icon fa fa-times"></i>
                                </button>

                                <strong>
                                    <i class="ace-icon fa fa-times"></i>
                                    Oh snap!
                                </strong>

                                Change a few things up and try submitting again.
                                <br />
                            </div>
                        }

                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.XMLFileLocation, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-xs-3">
                                    <input type="file" id="id-input-file-2" />
                                    <input type="hidden" value="@Model.XMLFileLocation" name="XMLFileLocation" id="XMLFileLocation" />
                                    <input type="hidden" value="defaultvalue" name="CSVFileLocation" id="CSVFileLocation" />
                                    <span id="uploadresult"></span>
                                    @Html.ValidationMessageFor(model => model.XMLFileLocation, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-xs-3">
                                    <img src="~/Content/Image/loading.gif" id="loadingImg" style="width:35px;height:35px;" />
                                </div>
                                
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" id="btnsubmit" class="btn btn-default" />
                                </div>
                            </div>
                        </div>

                    }
                </div>
            </div>          
        </div>
    </div>
</div>

@section Scripts {
    <!-- basic scripts -->
    <!--[if !IE]> -->
    <script src="/assets/js/jquery-2.1.4.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")

    <!-- <![endif]-->
    <!--[if IE]> to use
    <script src="assets/js/jquery-1.11.3.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        if ('ontouchstart' in document.documentElement) document.write("<script src='/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>
    <script src="/assets/js/bootstrap.min.js"></script>

    <!-- page specific plugin scripts -->
    <!--[if lte IE 8]>
      <script src="assets/js/excanvas.min.js"></script>
    <![endif]-->
    <script src="/assets/js/jquery-ui.custom.min.js"></script>
    <script src="/assets/js/jquery.ui.touch-punch.min.js"></script>
    <script src="/assets/js/chosen.jquery.min.js"></script>
    <script src="/assets/js/spinbox.min.js"></script>
    <script src="/assets/js/bootstrap-datepicker.min.js"></script>
    <script src="/assets/js/bootstrap-timepicker.min.js"></script>
    <script src="/assets/js/moment.min.js"></script>
    <script src="/assets/js/daterangepicker.min.js"></script>
    <script src="/assets/js/bootstrap-datetimepicker.min.js"></script>
    <script src="/assets/js/bootstrap-colorpicker.min.js"></script>
    <script src="/assets/js/jquery.knob.min.js"></script>
    <script src="/assets/js/autosize.min.js"></script>
    <script src="/assets/js/jquery.inputlimiter.min.js"></script>
    <script src="/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/assets/js/bootstrap-tag.min.js"></script>

    <script src="/Scripts/summernote.js"></script>
    <script src="/Scripts/script-custom-editor.js"></script>
    <link href="/css/summernote.css" rel="stylesheet" />   

    <!-- ace scripts -->
    <script src="/assets/js/ace-elements.min.js"></script>
    <script src="/assets/js/ace.min.js"></script>
    <script type="text/javascript">
        jQuery(function ($) {          
            $("#loadingImg").css("display", "none");
            $('#id-input-file-2').ace_file_input({
                no_file: 'No File ...',
                btn_choose: 'Choose',
                btn_change: 'Change',
                droppable: false,
                onchange: null,
                thumbnail: false, //| true | large
                //whitelist:'gif|png|jpg|jpeg'
                //blacklist:'exe|php'
                //onchange:''
                //
            }).on('change', function () {
                var files = $("#id-input-file-2").get(0).files;
                var fileData = new FormData();

                for (var i = 0; i < files.length; i++) {
                    fileData.append("fileInput", files[i]);
                }

                $.ajax({
                    type: "POST",
                    url: "/Assignment/UploadFiles",
                    dataType: "json",
                    contentType: false, // Not to set any content header
                    processData: false, // Not to process data
                    data: fileData,
                    success: function (result, status, xhr) {
                        $("#XMLFileLocation").val(result);
                        $("#uploadresult").html("<font color='green'>Uploaded successfully</font>");
                    },
                    error: function (xhr, status, error) {
                        if (xhr.responseText.indexOf("Invalid File Type") >= 0) {
                            $("#uploadresult").html("<font color='Red'>Unknown format</font>");
                        }
                        else {
                            $("#uploadresult").html(status);
                        }

                    }
                });
            });

            $(document).ajaxStart(function () {
                $("#loadingImg").show();
                $("#btnsubmit").prop('disabled', true);
            });

            $(document).ajaxStop(function () {
                $("#loadingImg").hide();
                $("#btnsubmit").prop('disabled', false);
            });           
        });
    </script>


}